<template>
  <div class="admin-page feedback-list-page">
    <section class="page-hero">
      <div class="page-hero__content">
        <div><div class="page-hero__eyebrow">Training Support</div><h1 class="page-hero__title">反馈工单</h1><p class="page-hero__subtitle">集中处理训练报告、动作和上传相关问题；身体不适记录已进入安全分流，不计入普通待办。</p><div class="page-hero__meta"><span class="page-pill">普通待办 {{ todoCount }} 条</span><span class="page-pill">安全记录 {{ safetyList.length }} 条</span></div></div>
        <div class="page-hero__side"><div class="hero-glass-card"><div class="hero-glass-card__label">7 天未跟进</div><div class="hero-glass-card__value">{{ closableCount }}</div><div class="hero-glass-card__hint">已回复工单可批量关闭</div></div></div>
      </div>
    </section>
    <el-card class="surface-card" shadow="never">
      <template #header><div class="section-header"><div><div class="section-header__title">{{ activeQueue === 'todo' ? '普通待办队列' : '安全分流记录' }}</div><div class="section-header__subtitle">{{ activeQueue === 'todo' ? '按待处理优先和患者最后留言时间排序。' : '患者已收到暂停训练和及时就医提示，默认不需人工处理。' }}</div></div><div class="toolbar-group"><el-button :type="activeQueue === 'todo' ? 'primary' : 'default'" @click="activeQueue = 'todo'">普通待办</el-button><el-button :type="activeQueue === 'safety' ? 'primary' : 'default'" @click="activeQueue = 'safety'">安全记录</el-button><el-button v-if="activeQueue === 'todo'" :disabled="!closableCount" @click="handleBatchClose">关闭 7 天未跟进</el-button><el-button type="primary" :loading="loading" @click="loadData">刷新</el-button></div></div></template>
      <div v-if="activeQueue === 'todo'" class="filter-shell"><el-input v-model="keyword" clearable placeholder="搜索工单号、患者姓名或患者 ID" style="width:260px" @keyup.enter="loadData"/><el-select v-model="filterStatus" clearable placeholder="状态" style="width:160px"><el-option label="待处理" value="pending"/><el-option label="处理中" value="processing"/><el-option label="已回复" value="replied"/><el-option label="已关闭" value="closed"/></el-select><el-select v-model="filterType" clearable placeholder="类型" style="width:190px"><el-option label="报告疑问" value="report_question"/><el-option label="动作问题" value="action_issue"/><el-option label="上传问题" value="upload_issue"/><el-option label="其他训练问题" value="other"/></el-select><el-checkbox v-model="showClosed">显示已关闭</el-checkbox></div>
      <div class="table-shell" v-loading="loading"><el-table :data="visibleList" stripe empty-text="暂无工单"><el-table-column label="患者" min-width="130"><template #default="{ row }"><strong>{{ row.patientName || `患者 #${row.patientId}` }}</strong><small class="cell-sub">#{{ row.patientId }}</small></template></el-table-column><el-table-column label="类型" min-width="120"><template #default="{ row }">{{ typeLabel(row.feedbackType) }}</template></el-table-column><el-table-column label="状态" width="110"><template #default="{ row }"><span class="soft-tag" :class="tagClass(row.status)">{{ statusLabel(row.status) }}</span></template></el-table-column><el-table-column label="关联训练" min-width="130"><template #default="{ row }"><span v-if="row.trainingContext">评分 {{ row.trainingContext.averageScore ?? '-' }} · {{ row.trainingContext.grade || '待评级' }}</span><span v-else>未关联</span></template></el-table-column><el-table-column label="最后留言" min-width="160"><template #default="{ row }">{{ formatDate(row.lastMessageAt || row.createdAt) }}</template></el-table-column><el-table-column label="摘要" min-width="260" show-overflow-tooltip><template #default="{ row }">{{ row.content }}</template></el-table-column><el-table-column label="操作" width="110" fixed="right"><template #default="{ row }"><el-button type="primary" link @click="router.push(`/feedback/${row.feedbackId}`)">查看工单</el-button></template></el-table-column></el-table></div>
    </el-card>
    <el-dialog v-model="detailVisible" width="860px" destroy-on-close title="工单处理"><div v-if="current" class="ticket-detail"><section class="ticket-context"><div><span>患者</span><strong>{{ current.patientName || `患者 #${current.patientId}` }}</strong></div><div><span>关联训练</span><strong>{{ current.trainingContext ? `${current.trainingContext.averageScore ?? '-'} 分 · ${current.trainingContext.grade || '待评级'}` : '未关联训练' }}</strong></div><div><span>当前状态</span><strong>{{ statusLabel(current.status) }}</strong></div></section><section class="ticket-timeline"><article v-for="message in current.messages || []" :key="message.messageId" class="ticket-message" :class="`ticket-message--${message.senderRole}`"><div><strong>{{ senderLabel(message.senderRole) }}</strong><small>{{ formatDate(message.createdAt) }}</small></div><p>{{ message.content }}</p><div v-if="message.imageUrls?.length" class="ticket-images"><el-image v-for="url in message.imageUrls" :key="url" :src="url" fit="cover" :preview-src-list="message.imageUrls"/></div></article></section><section v-if="current.handlingMode === 'manual' && current.status !== 'closed'" class="ticket-actions"><el-button v-if="current.status === 'pending'" @click="handleStart">开始处理</el-button><el-select v-model="selectedTemplate" clearable placeholder="选择回复模板" style="width:170px" @change="applyTemplate"><el-option v-for="template in templates" :key="template.code" :label="template.label" :value="template.code"/></el-select><el-input v-model="replyContent" type="textarea" :rows="4" maxlength="1000" show-word-limit placeholder="请输入训练指导回复，不提供诊断或治疗建议"/><div class="ticket-actions__buttons"><el-button v-if="current.status === 'replied'" @click="handleClose">关闭工单</el-button><el-button type="primary" :loading="saving" @click="handleReply">发送回复</el-button></div></section><section v-else-if="current.handlingMode === 'safety_auto'" class="safety-note">此记录已自动完成安全分流。患者已收到“暂停训练、及时就医”的系统提示。</section><section v-else class="safety-note">该工单已关闭，不能继续发送消息。</section></div></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import { useRouter } from 'vue-router';
import { ElMessage, ElMessageBox } from 'element-plus';
import type { AdminFeedbackListItemDto } from '@home-rehab-motion/shared-contract';
import type { FeedbackStatus, FeedbackType } from '@home-rehab-motion/shared-types';
import { batchCloseInactiveFeedback, closeFeedback, getFeedbackDetail, getFeedbackList, getReplyTemplates, replyFeedback, startFeedback, type ReplyTemplate } from '@/services/feedback';
const router = useRouter();
const activeQueue = ref<'todo' | 'safety'>('todo');
const keyword = ref(''); const list = ref<AdminFeedbackListItemDto[]>([]); const safetyList = ref<AdminFeedbackListItemDto[]>([]); const loading = ref(false); const detailVisible = ref(false); const current = ref<AdminFeedbackListItemDto | null>(null); const templates = ref<ReplyTemplate[]>([]); const selectedTemplate = ref(''); const replyContent = ref(''); const saving = ref(false); const filterStatus = ref<FeedbackStatus | ''>(''); const filterType = ref<FeedbackType | ''>(''); const showClosed = ref(false);
const todoCount = computed(() => list.value.filter((item) => item.status === 'pending' || item.status === 'processing').length); const sevenDaysAgo = computed(() => Date.now() - 7 * 24 * 60 * 60 * 1000); const closableCount = computed(() => list.value.filter((item) => item.status === 'replied' && new Date(item.lastMessageAt || item.createdAt || '').getTime() <= sevenDaysAgo.value).length); const visibleList = computed(() => (activeQueue.value === 'safety' ? safetyList.value : list.value).filter((item) => (showClosed.value || activeQueue.value === 'safety' || item.status !== 'closed') && (!filterStatus.value || item.status === filterStatus.value) && (!filterType.value || item.feedbackType === filterType.value)));
const typeLabel = (type: string) => ({ report_question: '报告疑问', action_issue: '动作问题', upload_issue: '上传问题', body_discomfort: '身体不适', other: '其他训练问题' }[type] || type); const statusLabel = (status: string) => ({ pending: '待处理', processing: '处理中', replied: '已回复', closed: '已关闭' }[status] || status); const tagClass = (status: string) => ({ pending: 'soft-tag--danger', processing: 'soft-tag--warning', replied: 'soft-tag--success', closed: 'soft-tag--info' }[status] || 'soft-tag--info'); const senderLabel = (role: string) => ({ patient: '患者', staff: '工作人员', system: '系统提示' }[role] || role); const formatDate = (value?: string) => value ? new Intl.DateTimeFormat('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }).format(new Date(value)) : '-';
async function loadData() { loading.value = true; try { [list.value, safetyList.value, templates.value] = await Promise.all([getFeedbackList(false, keyword.value), getFeedbackList(true, keyword.value), getReplyTemplates()]); } catch (error: any) { ElMessage.error(error?.response?.data?.message || '加载反馈工单失败'); } finally { loading.value = false; } }
async function openDetail(id: number) { current.value = await getFeedbackDetail(id); replyContent.value = ''; selectedTemplate.value = ''; detailVisible.value = true; }
function applyTemplate(code: string) { const selected = templates.value.find((item) => item.code === code); if (selected) replyContent.value = selected.content; }
async function refreshCurrent() { if (current.value) current.value = await getFeedbackDetail(current.value.feedbackId); await loadData(); }
async function handleStart() { if (!current.value) return; saving.value = true; try { await startFeedback(current.value.feedbackId); ElMessage.success('已开始处理'); await refreshCurrent(); } finally { saving.value = false; } }
async function handleReply() { if (!current.value || replyContent.value.trim().length < 1) { ElMessage.warning('回复至少需要 1 个字'); return; } saving.value = true; try { await replyFeedback(current.value.feedbackId, { content: replyContent.value, templateCode: selectedTemplate.value || undefined }); ElMessage.success('回复已发送，患者会收到消息中心通知'); replyContent.value = ''; await refreshCurrent(); } catch (error: any) { ElMessage.error(error?.response?.data?.message || '发送失败'); } finally { saving.value = false; } }
async function handleClose() { if (!current.value) return; await ElMessageBox.confirm('关闭后患者不能继续在该工单追问，确定关闭吗？', '关闭工单'); saving.value = true; try { await closeFeedback(current.value.feedbackId); ElMessage.success('工单已关闭'); await refreshCurrent(); } finally { saving.value = false; } }
async function handleBatchClose() { await ElMessageBox.confirm(`将关闭 ${closableCount.value} 条已回复且超过 7 天无新消息的工单。`, '批量关闭'); const result = await batchCloseInactiveFeedback(); ElMessage.success(`已关闭 ${result.closedCount} 条工单`); await loadData(); }
watch(activeQueue, () => { filterStatus.value = ''; filterType.value = ''; }); onMounted(loadData);
</script>
<style scoped>
.cell-sub{display:block;margin-top:3px;color:var(--ink-500);font-size:11px}.ticket-detail{display:grid;gap:16px}.ticket-context{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.ticket-context div{padding:12px;border-radius:12px;background:rgba(232,242,250,.72)}.ticket-context span,.ticket-message small{display:block;color:var(--ink-500);font-size:12px}.ticket-context strong{display:block;margin-top:6px;color:var(--ink-900);font-size:14px}.ticket-timeline{max-height:340px;overflow:auto;display:grid;gap:10px;padding-right:4px}.ticket-message{padding:14px 16px;border-radius:14px;background:#f5f8fb;border:1px solid rgba(148,180,214,.16)}.ticket-message--staff{background:rgba(51,178,123,.09);border-color:rgba(51,178,123,.2)}.ticket-message--system{background:rgba(240,166,63,.1);border-color:rgba(240,166,63,.2)}.ticket-message>div:first-child{display:flex;justify-content:space-between;gap:12px}.ticket-message p{margin:9px 0 0;white-space:pre-wrap;line-height:1.7}.ticket-images{display:flex;gap:8px;margin-top:10px}.ticket-images :deep(.el-image){width:70px;height:70px;border-radius:8px}.ticket-actions{display:grid;gap:12px;padding-top:16px;border-top:1px solid rgba(148,180,214,.18)}.ticket-actions__buttons{display:flex;justify-content:flex-end;gap:10px}.safety-note{padding:16px;border-radius:12px;background:rgba(240,166,63,.12);color:#895000;line-height:1.7}@media(max-width:700px){.ticket-context{grid-template-columns:1fr}}
</style>
