<template>
  <div class="admin-page guidance-list-page">
    <section class="page-hero"><div class="page-hero__content"><div><div class="page-hero__eyebrow">Content Library</div><h1 class="page-hero__title">指导内容管理</h1><p class="page-hero__subtitle">草稿与已发布版本独立维护，患者端只读取已发布版本。</p><div class="page-hero__meta"><span class="page-pill">当前内容 {{ list.length }} 条</span><span class="page-pill">草稿 / 校验 / 发布 / 回滚</span></div></div><div class="page-hero__side"><div class="hero-glass-card"><div class="hero-glass-card__label">已发布</div><div class="hero-glass-card__value">{{ publishedCount }}</div><div class="hero-glass-card__hint">患者当前可见的动作指导</div></div></div></div></section>
    <el-card class="surface-card" shadow="never"><template #header><div class="section-header"><div><div class="section-header__title">指导内容列表</div><div class="section-header__subtitle">创建和修改默认仅保存草稿，发布检查通过后才会上线。</div></div><div class="toolbar-group"><el-button @click="loadData" :loading="loading">刷新</el-button><el-button type="primary" @click="router.push('/guidance/create')">新建指导内容</el-button></div></div></template>
      <div class="table-shell" v-loading="loading"><el-table :data="list" stripe><el-table-column prop="contentId" label="ID" width="76"/><el-table-column prop="actionType" label="动作类型" min-width="130"><template #default="{row}">{{ actionTypeLabel(row.actionType) }}</template></el-table-column><el-table-column prop="title" label="标题" min-width="200"/><el-table-column label="线上版本" width="110"><template #default="{row}"><el-tag :type="row.published ? 'success' : 'info'">{{ row.published ? `V${row.publishedVersion}` : '未发布' }}</el-tag></template></el-table-column><el-table-column label="草稿" width="100"><template #default="{row}"><el-tag :type="row.hasDraft ? 'warning' : 'info'">{{ row.hasDraft ? '有草稿' : '无草稿' }}</el-tag></template></el-table-column><el-table-column prop="updatedAt" label="最近修改" min-width="170"><template #default="{row}">{{ formatDate(row.updatedAt) }}</template></el-table-column><el-table-column label="操作" width="180" fixed="right"><template #default="{row}"><el-button type="primary" link @click="router.push(`/guidance/${row.contentId}/edit`)">编辑</el-button><el-button type="primary" link @click="handleViewVersions(row.contentId)">版本</el-button><el-popconfirm title="确认永久删除该指导内容及其所有版本吗？" confirm-button-text="确认删除" cancel-button-text="取消" @confirm="handleDelete(row)"><template #reference><el-button type="danger" link>删除</el-button></template></el-popconfirm></template></el-table-column></el-table></div>
    </el-card>
    <el-dialog v-model="versionDialogVisible" title="已发布版本记录" width="620px"><el-table :data="versions" stripe size="small"><el-table-column prop="version" label="版本" width="90"><template #default="{row}">V{{row.version}}</template></el-table-column><el-table-column prop="createdAt" label="发布时间"><template #default="{row}">{{formatDate(row.createdAt)}}</template></el-table-column><el-table-column label="内容摘要" min-width="180"><template #default="{row}">{{row.snapshot.title}} · {{row.snapshot.steps.length}} 个步骤</template></el-table-column></el-table></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'; import { useRouter } from 'vue-router'; import { ElMessage } from 'element-plus';
import { deleteGuidance, getGuidanceList, getGuidanceVersions } from '@/services/guidance'; import type { AdminGuidanceListItemDto, GuidanceVersionDto } from '@home-rehab-motion/shared-contract'; import type { TrainingActionType } from '@home-rehab-motion/shared-types';
const router=useRouter(); const list=ref<AdminGuidanceListItemDto[]>([]); const loading=ref(false); const versionDialogVisible=ref(false); const versions=ref<GuidanceVersionDto[]>([]); const publishedCount=computed(()=>list.value.filter(item=>item.published).length);
function actionTypeLabel(type:TrainingActionType){return ({abdominal_crunch:'缩腹运动',pelvic_tilt:'骨盆倾斜',knee_rotation:'膝关节旋转'} as Record<string,string>)[type]||type;} function formatDate(value:string){return new Date(value).toLocaleString('zh-CN',{hour12:false});}
async function loadData(){loading.value=true;try{list.value=await getGuidanceList();}catch{ElMessage.error('获取指导内容失败');}finally{loading.value=false;}} async function handleViewVersions(id:number){try{versions.value=await getGuidanceVersions(id);versionDialogVisible.value=true;}catch{ElMessage.error('获取版本历史失败');}} async function handleDelete(row:AdminGuidanceListItemDto){loading.value=true;try{await deleteGuidance(row.contentId);ElMessage.success('指导内容已删除');await loadData();}catch(error:any){ElMessage.error(error?.response?.data?.message||'删除失败，请稍后重试');}finally{loading.value=false;}} onMounted(loadData);
</script>
