"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const appConfig_1 = require("../../services/appConfig");
const env_1 = require("../../config/env");
const guidance_1 = require("../../services/guidance");
const session_1 = require("../../store/session");
const DEFAULT_COVERS = { abdominal_crunch: '/guidance-defaults/cover-abdominal-crunch.png', pelvic_tilt: '/guidance-defaults/cover-pelvic-tilt.png', knee_rotation: '/guidance-defaults/cover-knee-rotation.png' };
const SHOOTING_DEFAULTS = {
  angle: { order: 1, typeLabel: '拍摄角度', title: '正侧面拍摄', description: '手机放在身体正侧方，与躯干保持平行。', altText: '训练者完整侧身站立，手机放在身体正侧方。', correctUrl: '../../assets/guidance/shooting-angle-side.png' },
  framing: { order: 2, typeLabel: '入镜范围', title: '全身完整入镜', description: '从头到脚都要拍到，四周留出适当空间。', altText: '训练者从头到脚完整出现在手机画面内。', correctUrl: '../../assets/guidance/shooting-framing-full-body.png' },
  lighting: { order: 3, typeLabel: '光线', title: '光线充足、画面明亮', description: '面向窗户或明亮光源，避免背光和阴影。', altText: '训练者面向明亮窗户，脸部和身体轮廓清晰。', correctUrl: '../../assets/guidance/shooting-lighting-bright.png' },
};
function getAppConfig() { const app = getApp(); return app.globalData.appConfig || appConfig_1.DEFAULT_APP_CONFIG; }
function resolveAssetUrl(url) { if (!url || /^https?:\/\//.test(url) || url.startsWith('data:')) return url || ''; const origin = env_1.API_BASE_URL.replace(/\/api\/?$/, ''); return `${origin}${url.startsWith('/') ? url : `/${url}`}`; }
function chooseTrainingVideo(source) { const cfg = getAppConfig(); const maxDuration = source === 'camera' ? cfg.videoRecordMaxDurationSeconds : cfg.videoMaxDurationSeconds; return new Promise((resolve, reject) => { const success = (res) => { const selected = res.tempFiles?.[0] || res; if (!selected?.tempFilePath) return reject(new Error('NO_VIDEO_SELECTED')); resolve({ tempFilePath: selected.tempFilePath, duration: Number(selected.duration || 0), size: Number(selected.size || 0) }); }; if (typeof wx.chooseMedia === 'function') return wx.chooseMedia({ count: 1, mediaType: ['video'], sourceType: [source], maxDuration, camera: 'back', success, fail: reject }); wx.chooseVideo({ sourceType: [source], maxDuration, camera: 'back', success, fail: reject }); }); }
function toShootingViewModel(requirements) { const byType = (requirements || []).reduce((result, item) => ({ ...result, [item.type]: item }), {}); return Object.keys(SHOOTING_DEFAULTS).map((type) => { const fallback = SHOOTING_DEFAULTS[type]; const item = byType[type] || {}; return { ...fallback, ...item, order: fallback.order, typeLabel: fallback.typeLabel, title: item.title || fallback.title, description: item.description || fallback.description, altText: item.altText || fallback.altText, correctUrl: resolveAssetUrl(item.correctImage?.url) || fallback.correctUrl }; }); }
function toViewModel(detail) { return { ...detail, coverUrl: resolveAssetUrl(detail.coverImage?.url) || resolveAssetUrl(DEFAULT_COVERS[detail.actionType]), videoUrl: resolveAssetUrl(detail.video?.asset?.url), videoFallbackText: detail.video?.fallbackText || '教学视频暂时无法播放，您可以先查看下面的图文步骤。', steps: (detail.steps || []).map((item, index) => ({ ...item, number: index + 1, imageUrl: resolveAssetUrl(item.image?.url) })), commonMistakes: (detail.commonMistakes || []).map((item) => ({ ...item, media: { ...item.media, url: resolveAssetUrl(item.media?.url) } })), hasCommonMistakes: (detail.commonMistakes || []).length > 0, shootingRequirements: toShootingViewModel(detail.shootingRequirements) }; }
function getNetworkType() { return new Promise((resolve) => wx.getNetworkType({ success: (result) => resolve(result.networkType || 'unknown'), fail: () => resolve('unknown') })); }
Page({
  data: { loading: true, failed: false, errorIcon: '⚠️', errorTitle: '', errorDesc: '', videoFailed: false, statusBarHeight: 20, navBarHeight: 44, topPlaceholderHeight: 128, detail: null, contentId: 0, actionType: '', loadedVersion: 0 },
  onReady() { this.updateTopPlaceholderHeight(); },
  onShow() { if (this.data.contentId) this.loadPublishedDetail(false); },
  async onLoad(query) { try { const app = getApp(); app.globalData.appConfig = await (0, appConfig_1.fetchAppConfig)(); } catch (_) {} const sysInfo = wx.getSystemInfoSync(); const statusBarHeight = sysInfo.statusBarHeight || 20; const capsule = wx.getMenuButtonBoundingClientRect?.(); const navBarHeight = capsule ? Math.max(44, capsule.height + (capsule.top - statusBarHeight) * 2) : 44; this.setData({ statusBarHeight, navBarHeight }); const contentId = Number(query.contentId || query.id); const actionType = String(query.actionType || ''); if (!contentId && !actionType) return this.setData({ loading: false, failed: true, errorIcon: '📋', errorTitle: '未找到动作指导', errorDesc: '请返回训练列表，选择需要练习的动作。' }); this.setData({ contentId, actionType }); await this.loadPublishedDetail(true); },
  async loadPublishedDetail(showLoading) { if (showLoading) this.setData({ loading: true, failed: false, errorTitle: '', errorDesc: '', videoFailed: false }); try { const detail = this.data.actionType ? await (0, guidance_1.getGuidanceDetailByAction)(this.data.actionType) : await (0, guidance_1.getGuidanceDetail)(this.data.contentId); const viewModel = toViewModel(detail); const changed = this.data.loadedVersion && this.data.loadedVersion !== (viewModel.version || 0); this.setData({ detail: viewModel, loadedVersion: viewModel.version || 0, loading: false, failed: false, videoFailed: false }); if (changed) wx.showToast({ title: `已更新至 V${viewModel.version}`, icon: 'none' }); } catch (error) { console.error('[动作指导加载失败]', error); if (showLoading) { const isOffline = (await getNetworkType()) === 'none'; this.setData({ loading: false, failed: true, errorIcon: isOffline ? '📡' : '⚠️', errorTitle: isOffline ? '网络连接不可用' : '动作指导暂时不可用', errorDesc: isOffline ? '请检查网络连接后重新加载。' : '服务可能正在繁忙或维护中，请稍后重新加载。' }); } } finally { this.updateTopPlaceholderHeight(); } },
  updateTopPlaceholderHeight() { wx.nextTick(() => wx.createSelectorQuery().select('.detail-top-sticky').boundingClientRect((rect) => { if (rect?.height) this.setData({ topPlaceholderHeight: Math.ceil(rect.height) }); }).exec()); },
  onGoBack() { wx.navigateBack({ delta: 1 }); }, onRetryLoad() { this.loadPublishedDetail(true); }, onVideoError() { this.setData({ videoFailed: true }); }, onPreviewImage(event) { const { url, urls } = event.currentTarget.dataset; if (url) wx.previewImage({ current: url, urls: urls || [url] }); },
  async onStartUpload() { await this.selectVideoAndGoUpload('camera'); }, async onChooseFromAlbum() { await this.selectVideoAndGoUpload('album'); },
  async selectVideoAndGoUpload(source) { if (!(0, session_1.getToken)()) { wx.showToast({ title: '登录后可提交训练视频', icon: 'none' }); wx.navigateTo({ url: '/pages/auth/login' }); return; } const detail = this.data.detail; if (!detail) return; wx.showLoading({ title: source === 'camera' ? '正在打开摄像头...' : '正在打开相册...' }); try { const video = await chooseTrainingVideo(source); (0, session_1.savePendingUploadDraft)({ actionType: detail.actionType, contentId: detail.contentId, tempFilePath: video.tempFilePath, duration: video.duration, size: video.size, source, updatedAt: Date.now() }); // 保留动作详情作为上传确认页的返回目的地；后续上传、分析、报告会逐页替换，不会累积中间页。
wx.navigateTo({ url: `/pages/upload/index?actionType=${detail.actionType}&contentId=${detail.contentId}&source=${source}` }); } catch (error) { const text = `${error?.errMsg || error?.message || ''}`; wx.showToast({ title: text.includes('cancel') ? (source === 'camera' ? '已取消录制' : '已取消选择') : (source === 'camera' ? '无法打开摄像头' : '无法打开相册'), icon: 'none' }); } finally { wx.hideLoading(); } },
});
